/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

/**
 *
 * @author VicDellaSala
 */
public class userInterface extends javax.swing.JFrame {

    /**
     * Creates new form userInterface
     */
    public userInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vs = new javax.swing.JLabel();
        AVictories = new javax.swing.JLabel();
        RSVictories = new javax.swing.JLabel();
        RSLogo = new javax.swing.JLabel();
        ALogo = new javax.swing.JLabel();
        aiStatusLabel = new javax.swing.JLabel();
        aiStatus = new javax.swing.JLabel();
        aiTimerLabel = new javax.swing.JLabel();
        aiTimeField = new javax.swing.JTextField();
        changeTimeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 190, 108));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vs.setFont(new java.awt.Font("Syne Medium", 3, 90)); // NOI18N
        vs.setText("VS");
        jPanel1.add(vs, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 150, -1));

        AVictories.setFont(new java.awt.Font("Syne Medium", 1, 24)); // NOI18N
        AVictories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AVictories.setText("0");
        jPanel1.add(AVictories, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 100, -1));

        RSVictories.setFont(new java.awt.Font("Syne Medium", 1, 24)); // NOI18N
        RSVictories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RSVictories.setText("0");
        jPanel1.add(RSVictories, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 110, -1));

        RSLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regular_Show_Logo-450.png"))); // NOI18N
        jPanel1.add(RSLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        ALogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Avatar-the-Last-Airbender-Symbol.png"))); // NOI18N
        jPanel1.add(ALogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, -1, 130));

        aiStatusLabel.setFont(new java.awt.Font("Syne Medium", 1, 18)); // NOI18N
        aiStatusLabel.setText("Estatus de la IA:");
        jPanel1.add(aiStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        aiStatus.setFont(new java.awt.Font("Syne Medium", 0, 18)); // NOI18N
        aiStatus.setText("Anunciando");
        jPanel1.add(aiStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 320, -1));

        aiTimerLabel.setFont(new java.awt.Font("Syne Medium", 1, 18)); // NOI18N
        aiTimerLabel.setText("Tiempo A.I.");
        jPanel1.add(aiTimerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        aiTimeField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(aiTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 120, -1));

        changeTimeButton.setText("Cambiar");
        changeTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTimeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(changeTimeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeTimeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeTimeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALogo;
    private javax.swing.JLabel AVictories;
    private javax.swing.JLabel RSLogo;
    private javax.swing.JLabel RSVictories;
    private javax.swing.JLabel aiStatus;
    private javax.swing.JLabel aiStatusLabel;
    private javax.swing.JTextField aiTimeField;
    private javax.swing.JLabel aiTimerLabel;
    private javax.swing.JButton changeTimeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel vs;
    // End of variables declaration//GEN-END:variables
}
